/**
* NewsAPI
* NewsAPI.org
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Source

import com.squareup.moshi.Json
/**
 * 
 * @param source 
 * @param author 
 * @param title 
 * @param description 
 * @param url 
 * @param urlToImage 
 * @param publishedAt 
 * @param content 
 */

data class Article (
    @Json(name = "source")
    val source: Source? = null,
    @Json(name = "author")
    val author: kotlin.String? = null,
    @Json(name = "title")
    val title: kotlin.String? = null,
    @Json(name = "description")
    val description: kotlin.String? = null,
    @Json(name = "url")
    val url: kotlin.String? = null,
    @Json(name = "urlToImage")
    val urlToImage: kotlin.String? = null,
    @Json(name = "publishedAt")
    val publishedAt: kotlin.String? = null,
    @Json(name = "content")
    val content: kotlin.String? = null
) 



