/**
* NewsAPI
* NewsAPI.org
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Article

import com.squareup.moshi.Json
/**
 * 
 * @param status 
 * @param totalResults 
 * @param articles 
 */

data class ArticleList (
    @Json(name = "status")
    val status: kotlin.String? = null,
    @Json(name = "totalResults")
    val totalResults: kotlin.Int? = null,
    @Json(name = "articles")
    val articles: kotlin.Array<Article>? = null
) 



