/**
* NewsAPI
* NewsAPI.org
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param message 
 * @param code 
 */

data class ErrorModel (
    @Json(name = "message")
    val message: kotlin.String,
    @Json(name = "code")
    val code: kotlin.Int
) 



